name: libumskt Build

on:
  schedule:
    - cron: "0 0 * * 0" # Run every Sunday at midnight
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source Tree
      uses: actions/checkout@v3

    - name: Clone UMSKT repository
      run: git clone https://github.com/UMSKT/UMSKT

    - name: Change directory to UMSKT
      run: cd UMSKT

    - name: Install required build tools
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          git \
          libssl-dev \
          mingw-w64

    - name: Configure and build UMSKT
      run: |
        cd build
        cmake ..
        make

    - name: Convert library to shared object
      run: |
        cd build
        gcc -shared -o libumskt.so lib_umskt.a
        i686-w64-mingw32-g++ -shared -o libumskt.dll libumskt.so

    - name: Move files to correct directory
      run: |
        mkdir -p build/actions_upload
        mv libumskt.so build/actions_upload/
        mv libumskt.dll build/actions_upload/

    - name: Upload build artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: libumskt-so
        path: build/actions_upload/libumskt.so

    - name: Upload build artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: libumskt-dll
        path: build/actions_upload/libumskt.dll
